type Course {
  id_course: Int!
  id_group: Int!
  id_area: Int!
  area: Area
  id_teacher: Int!
  teacher: Teacher
  name: String!
  position: Int
  dimension_code: Int
  dimension_type: String
  hour: Int!
  average: String
  percentage: Int
}

type Definitives {
  id_cour_stu: Int!
  id_student: Int
  id_course: Int
  score1: String
  score2: String
  score3: String
  score4: String
  score5: String
}

input CreateCourseInput {
  id_group: Int!
  id_teacher: Int!
  name: String!
  position: Int
  dimension_code: Int
  dimension_type: String
  id_area: Int!
  hour: Int!
  average: String
  percentage: Int
}

input UpdateCourseInput {
  id_course: Int!
  id_group: Int
  id_teacher: Int
  name: String
  position: Int
  dimension_code: Int
  dimension_type: String
  id_area: Int
  hour: Int
  average: String
  percentage: Int
}

input FilterCourseInput {
  id_group: Int
  id_teacher: Int
  name: String
  position: Int
  dimension_code: Int
  dimension_type: String
  id_area: Int
  hour: Int
  average: String
  percentage: Int
}

input UpdateDefinitivesInput {
  id_cour_stu: Int!
  score1: String
  score2: String
  score3: String
  score4: String
  score5: String
}

input FilterDefinitivesInput {
  id_student: Int
  id_course: Int
  score1: String
  score2: String
  score3: String
  score4: String
  score5: String
}

type Query {
  courses(filterCourseInput: FilterCourseInput): [Course]!
  courseByID(id_course: Int!): Course
  studentDefinitives(filterDefinitivesInput: FilterDefinitivesInput): [Definitives]!
}

type Mutation {
  createCourse(createCourseInput: CreateCourseInput!): Course!
  updateCourse(updateCourseInput: UpdateCourseInput!): Course!
  deleteCourse(id_course: Int!): Course
  updateDefitinives(updateDefinitivesInput: UpdateDefinitivesInput): Definitives!
}
