type Group {
  id_group: Int!
  id_year: Int
  level: Int
  sublevel: String
  working_time: String
  representative: String
}

input CreateGroupInput {
  id_year: Int!
  level: Int!
  sublevel: String!
  working_time: String
  representative: String!
}

input UpdateGroupInput {
  id_group: Int!
  working_time: String
  representative: String
}

input FilterGroupInput {
  id_year: Int
  level: Int
  sublevel: String
  working_time: String
  representative: String
}

type Query {
  groups(filterGroupInput: FilterGroupInput): [Group]!
  groupByID(id_group: Int!): Group
}

type Mutation {
  createGroup(createGroupInput: CreateGroupInput!): Group!
  updateGroup(updateGroupInput: UpdateGroupInput!): Group!
  deleteGroup(id_group: Int!): Group
}
