import { institution } from '@prisma/client';

export function globalNotesSheetByCourseTemplate(
  data: any[],
  institution: institution,
): string {
  return `<html><head><style>body {transition: opacity ease-in 0.2s; } 
body[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } 
</style>
<title>Imprimir</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<style>
H1.SaltoDePagina { PAGE-BREAK-AFTER: always }
</style>

<style type="text/css">
<!--
body,td,th {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 10px;
	
}
h1 {
	font-size: 10px;
	}
	
h2 {
font-size: 11px;
}

.pie
{
	font-size: 10px;
	font-weight:bold;  
    
}

.cabeza
{
	font-size: 12px;
	    
}


-->
</style>
</head>
<body bottommargin="0" leftmargin="0" rightmargin="0" topmargin="0">

<table align="center" width="650">
	<tbody><tr>
	 <td valign="top">		
	<br><center>
	  <font size="5">INSTITUCIÓN EDUCATIVA GIMNASIO DEL SAN JORGE  </font><br>
		<font size="4"> Asignaturas  Parvulo A Mañana año 2022<br> Para el periodo 2 </font><br><br>
		
		<br><div align="justify"> <b>1. </b> Matemáticas<br> <b>2. </b> Lengua Castellana<br> <b>3. </b> Inglés<br> <b>4. </b> Ciencias Sociales<br> <b>5. </b> Ciencias Naturales Y Educación Ambiental<br> <b>6. </b> Tecnología E Informatica<br> <b>7. </b> Educación Ética Y Valores Humanos<br> <b>8. </b> Educación Religiosa<br> <b>9. </b> Educación Artística<br> <b>10. </b> Educación Física, Recreación Y Deportes<br> <b>11. </b> Desarrollo Cognitivo<br> <b>12. </b> Desarrollo Psicomotriz<br> <b>13. </b> Desarrollo Socio Afectivo<br> <b>14. </b> Desarrollo Físico<br> <b>15. </b> Habilidades Comunicativas<br> <b>16. </b> Conducta<br> <b>17. </b> Disciplina<br> <table align="center" width="98%" border="1" cellpadding="3" cellspacing="0">	
		<tbody><tr>
		 <td></td>
		<td><div align="center"><strong>Apellido - Nombres </strong></div></td>
		<td><center>1</center></td><td><center>2</center></td><td><center>3</center></td><td><center>4</center></td><td><center>5</center></td><td><center>6</center></td><td><center>7</center></td><td><center>8</center></td><td><center>9</center></td><td><center>10</center></td><td><center>11</center></td><td><center>12</center></td><td><center>13</center></td><td><center>14</center></td><td><center>15</center></td><td><center>16</center></td><td><center>17</center></td>
		   
		 </tr><tr>
			<td><div align="center"><strong>1</strong></div></td>
			<td>Alvarez Mariano Antonio</td><td><div align="center"><strong>4.3</strong></div></td><td><div align="center"><strong>4.3</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.3</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr><tr>
			<td><div align="center"><strong>2</strong></div></td>
			<td>Arcia Hernandez  Ian</td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.3</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr><tr>
			<td><div align="center"><strong>3</strong></div></td>
			<td>Banquet Vergara  Emma Sofia</td><td><div align="center"><strong>4.4</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr><tr>
			<td><div align="center"><strong>4</strong></div></td>
			<td>Castillo Vergara Luis Alejandro </td><td><div align="center"><strong>4.3</strong></div></td><td><div align="center"><strong>4.3</strong></div></td><td><div align="center"><strong>4.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr><tr>
			<td><div align="center"><strong>5</strong></div></td>
			<td>Cobos Alean Benjamin</td><td><div align="center"><strong>4.0</strong></div></td><td><div align="center"><strong>4.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr><tr>
			<td><div align="center"><strong>6</strong></div></td>
			<td>De Hoyos Gomez  Thomas David</td><td><div align="center"><strong>4.0</strong></div></td><td><div align="center"><strong>4.0</strong></div></td><td><div align="center"><strong>4.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.8</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr><tr>
			<td><div align="center"><strong>7</strong></div></td>
			<td>Diaz Castillo Alba Alisha</td><td><div align="center"><strong>4.3</strong></div></td><td><div align="center"><strong>4.3</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr><tr>
			<td><div align="center"><strong>8</strong></div></td>
			<td>Gonzalez Contreras Samuel </td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr><tr>
			<td><div align="center"><strong>9</strong></div></td>
			<td>Lazaro Acevedo Juan Diego</td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.0</strong></div></td><td><div align="center"><strong>4.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr><tr>
			<td><div align="center"><strong>10</strong></div></td>
			<td>Leon Villadiego  Luciana </td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.0</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr><tr>
			<td><div align="center"><strong>11</strong></div></td>
			<td>Manjarres GÁmez Ina Vanessa</td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.3</strong></div></td><td><div align="center"><strong>4.3</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr><tr>
			<td><div align="center"><strong>12</strong></div></td>
			<td>Monterrosa  Bueno Hernan David </td><td><div align="center"><strong>4.2</strong></div></td><td><div align="center"><strong>4.0</strong></div></td><td><div align="center"><strong>4.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr><tr>
			<td><div align="center"><strong>13</strong></div></td>
			<td>Ortega Caballero Jeronimo</td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.3</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr><tr>
			<td><div align="center"><strong>14</strong></div></td>
			<td>Prasca Alvarez Luis Angel </td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.3</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr><tr>
			<td><div align="center"><strong>15</strong></div></td>
			<td>Ricardo Arrieta Ana Paulina </td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.3</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr><tr>
			<td><div align="center"><strong>16</strong></div></td>
			<td>Salgado Pacheco Jaziel Florentino</td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td></tr><tr>
			<td><div align="center"><strong>17</strong></div></td>
			<td>Severiche Quintero Maximiliano</td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td></tr><tr>
			<td><div align="center"><strong>18</strong></div></td>
			<td>Tanus Acosta Jorge Andres</td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.0</strong></div></td><td><div align="center"><strong>4.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr><tr>
			<td><div align="center"><strong>19</strong></div></td>
			<td>Zuluaga Fernandez  Violeta</td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>4.3</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>4.6</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>4.5</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>&nbsp;</strong></div></td><td><div align="center"><strong>5.0</strong></div></td><td><div align="center"><strong>5.0</strong></div></td></tr></tbody></table><br><br> 	 
	 </div></center></td>
	</tr>
</tbody></table>


</body></html>`;
}
