
const policies = {
  Query: {
    achievements: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    achievementByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    users: { requires: ['Administrator', 'Secretary'] },
    userByID: { requires: ['Administrator', 'Secretary'] },
    typeQualifications: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    typeQualificationByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    teachers: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    teacherByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    students: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    studentByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    scholarYears: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    scholarYearByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    recommendationStudents: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    recommendationStudentByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    recommendations: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    recommendationByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    observations: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    observationByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    indicatorStudents: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    indicatorStudentByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    groups: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    groupByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    featured: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    featuredByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    enrollments: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    enrollmentByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    courseStudents: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    courseStudentsByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    courses: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    courseByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    areas: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    areaByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    achievementStudents: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    achievementStudentsByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    absences: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    absenceByID: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
  },
  Mutation: {
    createAchievement: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateAchievement: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteAchievement: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    createUser: { requires: ['Administrator', 'Secretary'] },
    updateUser: { requires: ['Administrator', 'Secretary'] },
    deleteUser: { requires: ['Administrator', 'Secretary'] },
    createTypeQualification: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateTypeQualification: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteTypeQualification: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    createTeacher: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateTeacher: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteTeacher: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    createStudent: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateStudent: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteStudent: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    createScholarYear: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateScholarYear: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteScholarYear: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    createRecommendationStudent: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateRecommendationStudent: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteRecommendationStudent: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    createRecommendation: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateRecommendation: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteRecommendation: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    createObservation: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateObservation: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteObservation: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    createIndicatorStudent: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateIndicatorStudent: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteIndicatorStudent: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    createGroup: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateGroup: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteGroup: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    createFeatured: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateFeatured: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteFeatured: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    createEnrollment: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateEnrollment: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteEnrollment: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    createCourseStudent: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateCourseStudent: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteCourseStudent: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    createCourse: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateCourse: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteCourse: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    createArea: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateArea: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteArea: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    createAchievementStudent: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateAchievementStudent: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteAchievementStudent: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    createAbsence: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    updateAbsence: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
    deleteAbsence: { requires: ['Administrator', 'Secretary', 'Teacher', 'Student'] },
  }
}

export default policies
