type Enrollment {
  id_enrollment: Int!
  id_student: Int
  id_group: Int
  year: Int
  status: String
  reason_desertion: String
  date_desertion: String
}

input CreateEnrollmentInput {
  id_student: Int!
  id_group: Int!
  year: Int
  status: String
  reason_desertion: String
  date_desertion: String
}

input UpdateEnrollmentInput {
  id_enrollment: Int!
  status: String
  reason_desertion: String
  date_desertion: String
}

input FilterEnrollmentInput {
  id_student: Int
  id_group: Int
  year: Int
  status: String
  reason_desertion: String
  date_desertion: String
}

type Query {
  enrollments(filterEnrollmentInput: FilterEnrollmentInput): [Enrollment]!
  enrollmentByID(id_enrollment: Int!): Enrollment
}

type Mutation {
  createEnrollment(createEnrollmentInput: CreateEnrollmentInput!): Enrollment!
  updateEnrollment(updateEnrollmentInput: UpdateEnrollmentInput!): Enrollment!
  deleteEnrollment(id_enrollment: Int!): Enrollment
}
