type Report {
  report_content: String!
}

input GenerateStudentsListUndeterminatedInput {
  id_group: Int!
}

input GenerateStudentsListDeterminatedInput {
  id_course: Int!
  id_group: Int!
}

input GenerateAchievementsAndIndicators {
  id_group: Int!
  id_course: Int!
  period: Int!
}

input GenerateReportAreaInput {
  id_group: Int!
  id_student: Int
  report_options: ReportDictionary!
}

input CertifiedStudentReportInput {
  id_student: Int!
  report_options: CertifiedStudentDictonary
}

input ReportDictionary {
  signature: SignatureInput!
  average_general: Boolean
  average_group: Boolean
  average_area: Boolean
  position: Boolean
  username: Boolean
  qualification_per1: Boolean
  qualification_per2: Boolean
  qualification_per3: Boolean
  qualification_per4: Boolean
  average_per: Boolean
  all_qualifications: Boolean
  professor_course: Boolean
  hour: Boolean
  absences: Boolean
}

input SignatureInput {
  professor_group: Boolean
  secretary: Boolean
  rector: Boolean
}

enum GradeDisplayMode {
  numerica_desempeno
  numerica
  desempeno
}

input CertifiedStudentDictonary {
  # Campos de ReportDictionary
  signature: SignatureInput!
  average_general: Boolean
  average_group: Boolean
  average_area: Boolean
  position: Boolean
  username: Boolean
  qualification_per1: Boolean
  qualification_per2: Boolean
  qualification_per3: Boolean
  qualification_per4: Boolean
  average_per: Boolean
  all_qualifications: Boolean
  professor_course: Boolean
  hour: Boolean
  absences: Boolean
  gradeDisplayConfig: GradeDisplayMode!
}
type Query {
  generateStudentsListUndeterminated(
    generateStudentsListUndeterminatedInput: GenerateStudentsListUndeterminatedInput
  ): Report!
  generateStudentsListDeterminated(
    generateStudentsListDeterminatedInput: GenerateStudentsListDeterminatedInput
  ): Report!
  generateAchievementsAndIndicators(
    generateAchievementsAndIndicators: GenerateAchievementsAndIndicators
  ): Report!
  generateReportArea(generateReportAreaInput: GenerateReportAreaInput): Report!

  generateStudentEnrollmentReportI(id_student: Int): Report!
  generateStudentEnrollmentReportII(id_student: Int): Report!

  
  generateCertifiedStudentReport(
    generateCertifiedStudentReportInput: CertifiedStudentReportInput
  ): Report!

}
