type ResumeDefinitive {
  score1: String
  score2: String
  score3: String
  score4: String
}

type ResumeCourse {
  id_course: Int
  name: String
  teacher: String
  definitives: ResumeDefinitive
}

type ResumeGroup {
  id_group: Int
  level: Int
  sublevel: String
  courses: [ResumeCourse]
}

type Student {
  id_student: Int!
  name: String
  last_name: String
  type_id: Int
  identification: String
  sex: String
  direction: String
  phone: String
  guardian: String
  status: String
  birthday: String
  father: String
  mother: String
  email: String
  groups: [ResumeGroup]
}

input CreateStudentInput {
  name: String!
  last_name: String!
  type_id: Int!
  identification: String!
  sex: String!
  direction: String
  phone: String!
  guardian: String!
  status: String
  birthday: String
  father: String
  mother: String
  email: String
}

input UpdateStudentInput {
  id_student: Int!
  name: String
  last_name: String
  type_id: Int
  identification: String
  sex: String
  direction: String
  phone: String
  guardian: String
  status: String
  birthday: String
  father: String
  mother: String
  email: String
}

input FilterStudentInput {
  name: String
  identification: String
}

type Query {
  studentsByGroup(id_group: Int!): [Student]!
  studentByID(id_student: Int!): Student
}

type Mutation {
  createStudent(createStudentInput: CreateStudentInput!, id_group: Int!): Student!
  updateStudent(updateStudentInput: UpdateStudentInput!): Student!
  deleteStudent(id_student: Int!): Student
}
