type Teacher {
  id_teacher: Int!
  name: String
  last_name: String
  type_id: Int
  identification: String
  direction: String
  phone: String
  email: String
  degree: String
}

input CreateTeacherInput {
  name: String!
  last_name: String!
  type_id: Int!
  identification: String!
  direction: String
  phone: String!
  email: String
  degree: String
}

input UpdateTeacherInput {
  id_teacher: Int!
  name: String
  last_name: String
  type_id: Int
  identification: String
  direction: String
  phone: String
  email: String
  degree: String
}

input FilterTeacherInput {
  name: String
  last_name: String
  type_id: Int
  identification: String
  direction: String
  phone: String
  email: String
  degree: String
}

type Query {
  teachers(filterTeacherInput: FilterTeacherInput): [Teacher]!
  teacherByID(id_teacher: Int!): Teacher
}

type Mutation {
  createTeacher(createTeacherInput: CreateTeacherInput!): Teacher!
  updateTeacher(updateTeacherInput: UpdateTeacherInput!): Teacher!
  deleteTeacher(id_teacher: Int!): Teacher
}
